#!/usr/bin/env python3
"""Generate the health promise register view and catch unregistered jobs.

Declared, not inferred: ``core/health/promises.py`` is the truth about what
each background job promises. This script is the inference side — it scans
the shipped tree for launchd job labels and fails when a job exists that
never registered a promise, so the register cannot silently fall behind the
code. It also verifies the bash mirror in
``.claude/hooks/session-start.sh`` (kept for bare-sandbox operation) still
matches the register, so the in-session glance and Doctor cannot drift
apart. With ``--write`` it renders ``docs/architecture/HEALTH-PROMISES.md``;
with ``--check`` it verifies the rendered view is current (CI drift gate).

Coverage boundary: the scan reads shipped ``.plist``/``.plist.template``
files and ``.sh`` installers. A launchd job introduced from another language
must add its promise to the register deliberately.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "docs" / "architecture" / "HEALTH-PROMISES.md"
SESSION_START = REPO_ROOT / ".claude" / "hooks" / "session-start.sh"
LABEL_PATTERN = re.compile(r"com\.dex\.[a-z0-9][a-z0-9-]*")
# Files that can introduce a launchd job.
CANDIDATE_SUFFIXES = (".plist", ".plist.template", ".sh")
MIRROR_ROW = re.compile(
    r"^(?P<label>com\.dex\.[a-z0-9-]+)\|(?P<path>[^|]+)\|(?P<seconds>\d+)\|[^|]+\|[^|]+\|(?P<mode>[A-Za-z:_-]+)$",
    re.MULTILINE,
)


def _tracked_files() -> list[Path]:
    sys.path.insert(0, str(REPO_ROOT))
    from core.utils.local_git import git_output

    listing = git_output(REPO_ROOT, "ls-files", "-z", profile="read-only")
    return [
        REPO_ROOT / name.decode("utf-8", "surrogateescape")
        for name in listing.split(b"\0")
        if name
    ]


def discovered_labels() -> dict[str, list[str]]:
    """Scan shipped installers and templates for launchd job labels."""
    found: dict[str, list[str]] = {}
    for path in _tracked_files():
        if not path.name.endswith(CANDIDATE_SUFFIXES):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if "launchctl" not in text and not path.name.endswith((".plist", ".plist.template")):
            continue
        for label in LABEL_PATTERN.findall(text):
            found.setdefault(label, []).append(path.relative_to(REPO_ROOT).as_posix())
    return found


def session_start_mirror_errors(promises) -> list[str]:
    """The bash staleness table must agree with the register it mirrors."""
    try:
        text = SESSION_START.read_text(encoding="utf-8")
    except OSError as error:
        return [f"session-start.sh could not be read: {error}"]
    rows = {match.group("label"): match for match in MIRROR_ROW.finditer(text)}
    errors: list[str] = []
    for promise in promises:
        if promise.receipt_kind == "daemon":
            if promise.id in rows:
                errors.append(f"{promise.id} is a daemon and must not be in the session-start staleness table")
            continue
        row = rows.pop(promise.id, None)
        if row is None:
            errors.append(f"{promise.id} is registered but missing from the session-start staleness table")
            continue
        expected_seconds = int(promise.cadence.total_seconds())
        if int(row.group("seconds")) != expected_seconds:
            errors.append(
                f"{promise.id}: session-start cadence {row.group('seconds')}s disagrees with the register ({expected_seconds}s)"
            )
        if row.group("path") != promise.receipt_path:
            errors.append(
                f"{promise.id}: session-start receipt path {row.group('path')!r} disagrees with the register ({promise.receipt_path!r})"
            )
        if promise.receipt_kind == "json-timestamp":
            expected_mode = f"json:{promise.receipt_key}"
        elif promise.activity_only:
            expected_mode = "mtime"
        else:
            expected_mode = "mtime-success"
        if row.group("mode") != expected_mode:
            errors.append(
                f"{promise.id}: session-start mode {row.group('mode')!r} disagrees with the register ({expected_mode!r})"
            )
    registered = {promise.id for promise in promises}
    for extra in rows:
        if extra not in registered:
            errors.append(f"session-start staleness table names unregistered job {extra}")
    return errors


def render(promises, labels: dict[str, list[str]]) -> str:
    lines = [
        "# Health promises (generated)",
        "",
        "> Generated by `scripts/generate-health-promises.py --write`; do not edit.",
        "> The register itself lives in `core/health/promises.py`.",
        "",
        "Every recurring background job in Dex declares one promise: how often it",
        "succeeds, and where a *completed* run writes its receipt. Doctor's",
        "background-job freshness check — which Proactive Health snapshots and the",
        "in-session pulse reads — audits these receipts. A growing log is activity,",
        "not health; only receipts count, and activity-only entries say so.",
        "",
        "| Job | Promise | Cadence | Receipt | Proves |",
        "| --- | --- | --- | --- | --- |",
    ]
    for promise in promises:
        if promise.receipt_kind == "daemon":
            cadence = "continuous"
            proves = "liveness only (launchd)"
        else:
            hours = promise.cadence.total_seconds() / 3600
            cadence = f"every {hours:g} h"
            proves = "activity only" if promise.activity_only else "a completed run"
        receipt = f"`{promise.receipt_path}`"
        if promise.receipt_key:
            receipt += f" → `{promise.receipt_key}`"
        lines.append(
            f"| `{promise.id}` | {promise.label} | {cadence} | {receipt} | {proves} |"
        )
    lines.extend(
        [
            "",
            "## Where each job is declared",
            "",
        ]
    )
    for label in sorted(labels):
        sources = ", ".join(f"`{source}`" for source in sorted(set(labels[label])))
        lines.append(f"- `{label}`: {sources}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    sys.path.insert(0, str(REPO_ROOT))
    from core.health.promises import PROMISES

    try:
        labels = discovered_labels()
    except Exception as error:  # noqa: BLE001 - a broken scan is a failed gate, not a traceback
        print(f"❌ health promise scan could not run: {error}", file=sys.stderr)
        return 1
    registered = {promise.id for promise in PROMISES}
    failed = False
    for label in sorted(set(labels) - registered):
        sources = ", ".join(sorted(set(labels[label])))
        print(
            f"❌ background job {label} (declared in {sources}) has no entry in "
            "core/health/promises.py — register its success receipt so health "
            "checks can audit it",
            file=sys.stderr,
        )
        failed = True
    for label in sorted(registered - set(labels)):
        print(
            f"❌ promise {label} is registered but no shipped installer or "
            "template declares that job — remove the stale entry",
            file=sys.stderr,
        )
        failed = True
    for error in session_start_mirror_errors(PROMISES):
        print(f"❌ {error}", file=sys.stderr)
        failed = True
    if failed:
        return 1

    rendered = render(PROMISES, labels)
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"Wrote {OUTPUT}")
        return 0
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current != rendered:
        print(
            "❌ docs/architecture/HEALTH-PROMISES.md is stale; run "
            "python3 scripts/generate-health-promises.py --write and commit",
            file=sys.stderr,
        )
        return 1
    print("Health promise register is current and complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
