"""Contract tests for .ci/test-durations.json (CI shard balance data).

The durations file is machine-generated by scripts/generate-test-durations.py
and is scanned by every tracked-tree gate like any other file. These tests pin
the contract that makes that safe: the file may only ever contain
plain-nodeid -> number pairs, with scanner-hostile nodeids (assembled secret
fixtures, personal-path fixtures) excluded at generation time rather than
allowlisted in the scanners. A hand edit that violates the contract fails here
before it reaches a scanner.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DURATIONS_PATH = REPO_ROOT / ".ci" / "test-durations.json"

NODEID_PREFIX = re.compile(r"^core/(tests|mcp/tests|migrations/tests)/[A-Za-z0-9_/]+\.py::")
SAFE_KEY = re.compile(r"^[A-Za-z0-9_/.:@,\[\]-]+$")
# Assembled from pieces so the literal form never lands in the tracked tree
# (mirrors scripts/generate-test-durations.py).
REJECT_SUBSTRINGS = ("/" + "Users" + "/", "HOME")


def _load() -> dict:
    return json.loads(DURATIONS_PATH.read_text(encoding="utf-8"))


def test_durations_file_is_a_flat_string_to_number_map() -> None:
    data = _load()
    assert isinstance(data, dict) and data
    for key, value in data.items():
        assert isinstance(key, str), f"non-string key: {key!r}"
        assert isinstance(value, (int, float)) and value >= 0, f"bad duration for {key!r}: {value!r}"


def test_every_key_is_a_plain_test_nodeid_within_the_sharded_suites() -> None:
    for key in _load():
        assert NODEID_PREFIX.match(key), f"key is not a nodeid inside the sharded test roots: {key!r}"


def test_no_key_carries_scanner_hostile_content() -> None:
    for key in _load():
        assert SAFE_KEY.match(key), f"key contains characters the generator must drop: {key!r}"
        assert not any(s in key for s in REJECT_SUBSTRINGS), f"key embeds a personal path form: {key!r}"
